### PR TITLE
Mapping

### PR DESCRIPTION
**Pull request by Marysteph**

### CODE REVIEW

**Comment by Marysteph** [comment]
@tkosciol please check this one out

**Comment by tkosciolek** [comment]
addressing issues #2 and #6

**Review by tkosciolek — COMMENTED** [review]
just one comment, really. Would it make sense to rename `Dockerfile` to something more telling? I don't know what the convention is, but maybe `genes_MAGS_eggNOG_mapping.docker` would be more appropriate?

**Comment by tkosciolek** [comment]
@Marysteph please lmk when ready to merge. looks good to me now

**Review by Marysteph — COMMENTED** [review]
@tkosciol

**Comment by Marysteph** [comment]
@tkosciol I think its ready to merge.

**Pull request merged**
